/** Copyright (C) 2022  Frieder Pankratz <frieder.pankratz@gmail.com> **/

#ifndef TRAACTMULTI_TRAACT_KINECT_AZURE_SRC_KINECTAZURESTATICDATA_H_
#define TRAACTMULTI_TRAACT_KINECT_AZURE_SRC_KINECTAZURESTATICDATA_H_

#endif //TRAACTMULTI_TRAACT_KINECT_AZURE_SRC_KINECTAZURESTATICDATA_H_
